remote_theme: jekyll/minima

title: vijayp.dev
description: > # this means to ignore newlines until "show_excerpts:"
  Been coding since I can remember. Currently a professional software
  engineer for over 10 years, primarily working in backend development
  using .NET. Site is extremely WIP.
show_excerpts: true # set to true to show excerpts on the homepage
google_analytics: UA-157461519-1 # TODO: Figure out how to use a different analytics service for this.

author:
  name: Vijay Prakash
  #email: me@vijayp.dev

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github: arnath
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: vpdev
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

disqus:
  shortname: vijayp-dev

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:

plugins:
 - jekyll-feed
 - jekyll-seo-tag
